"""fresh_start

Revision ID: 5c5c11cb413c
Revises: 
Create Date: 2026-01-24 15:09:12.121390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c5c11cb413c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_logs_id'), 'command_logs', ['id'], unique=False)
    op.create_table('streamers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_streamers_id'), 'streamers', ['id'], unique=False)
    op.create_table('viewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('platform_user_id', sa.String(), nullable=True),
    sa.Column('is_subscriber', sa.Boolean(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_user_id')
    )
    op.create_index(op.f('ix_viewers_id'), 'viewers', ['id'], unique=False)
    op.create_table('communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streamer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('culture_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['streamer_id'], ['streamers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communities_id'), 'communities', ['id'], unique=False)
    op.create_table('stream_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streamer_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avg_viewers', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['streamer_id'], ['streamers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_sessions_id'), 'stream_sessions', ['id'], unique=False)
    op.create_table('commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_session_id', sa.Integer(), nullable=False),
    sa.Column('issued_by_type', sa.String(), nullable=True),
    sa.Column('issued_by_id', sa.Integer(), nullable=True),
    sa.Column('command_text', sa.String(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('execution_target', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stream_session_id'], ['stream_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commands_id'), 'commands', ['id'], unique=False)
    op.create_table('command_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('response_text', sa.String(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_results_id'), 'command_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_command_results_id'), table_name='command_results')
    op.drop_table('command_results')
    op.drop_index(op.f('ix_commands_id'), table_name='commands')
    op.drop_table('commands')
    op.drop_index(op.f('ix_stream_sessions_id'), table_name='stream_sessions')
    op.drop_table('stream_sessions')
    op.drop_index(op.f('ix_communities_id'), table_name='communities')
    op.drop_table('communities')
    op.drop_index(op.f('ix_viewers_id'), table_name='viewers')
    op.drop_table('viewers')
    op.drop_index(op.f('ix_streamers_id'), table_name='streamers')
    op.drop_table('streamers')
    op.drop_index(op.f('ix_command_logs_id'), table_name='command_logs')
    op.drop_table('command_logs')
    # ### end Alembic commands ###
