export const pricingData = {
  currency: "USD",
  annualDiscountPercent: 18,
  viewerPlans: [
    {
      id: "viewer_free",
      name: "Viewer Free",
      priceMonthly: 0,
      priceAnnual: 0,
      limits: [
        "10 AI asks/day",
        "25 saved moments total",
        "3 exports/month",
        "30 votes/day",
        "20 commands/day",
        "24h event history",
      ],
      features: ["Live event feed", "Basic trust panel", "Core viewer actions"],
      cta: "Start Free",
    },
    {
      id: "viewer_plus",
      name: "Viewer Plus",
      priceMonthly: 7.99,
      priceAnnual: 79,
      limits: [
        "150 AI asks/day",
        "500 saved moments total",
        "40 exports/month",
        "300 votes/day",
        "200 commands/day",
        "30-day event history",
      ],
      features: ["Priority queue (2x)", "Advanced recap summaries", "Expanded export limits"],
      cta: "Get Viewer Plus",
      popular: true,
    },
  ],
  streamerPlans: [
    {
      id: "streamer_free",
      name: "Streamer Free",
      priceMonthly: 0,
      priceAnnual: 0,
      limits: [
        "1 channel",
        "20 live hours/month",
        "100 viewer MAU included",
        "5 automation rules",
        "20 clip exports/month",
        "7-day analytics retention",
      ],
      features: ["Starter moderation", "Core automation", "Single seat"],
      cta: "Launch Free",
    },
    {
      id: "streamer_starter",
      name: "Streamer Starter",
      priceMonthly: 19,
      priceAnnual: 190,
      limits: [
        "1 channel",
        "120 live hours/month",
        "250 viewer MAU included",
        "20 automation rules",
        "100 clip exports/month",
        "30-day analytics retention",
      ],
      features: ["Twitch + YouTube integrations", "Expanded moderation retention", "Single seat"],
      cta: "Choose Starter",
      popular: true,
    },
    {
      id: "streamer_pro",
      name: "Streamer Pro",
      priceMonthly: 49,
      priceAnnual: 490,
      limits: [
        "3 channels",
        "400 live hours/month",
        "2,000 viewer MAU included",
        "200 automation rules",
        "500 clip exports/month",
        "12-month analytics retention",
      ],
      features: ["Priority processing", "90-day moderation retention", "3 team seats"],
      cta: "Choose Pro",
    },
  ],
};
